### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by KerstinMaur** [MarvinStelter/DieDreiFragezeichenEinschlafhilfe#1]
Erstmal vielen Dank für die tolle App, Marvin! 👍
Wärst du damit einverstanden, wenn die App in [F-Droid](https://f-droid.org/) aufgenommen wird?
Dann würde ich das sehr gerne in die Wege leiten.

**Comment by KerstinMaur** [comment]
Könntest du die Builds neben Google Play auch bei [GitHub getaggt veröffentlichen](https://github.com/MarvinStelter/DieDreiFragezeichenEinschlafhilfe/releases)?
Wo stehen eigentlich die Versionsinformationen? In der build.gradle habe ich nichts gefunden.
Hast du auch eine [PayPal.Me-Adresse](https://www.paypal.me/)?
Vielen Dank.

**Comment by DonMarv00** [comment]
Hey,
Ja von mir aus ginge das in Ordnung :)
Die Builds kann ich die nächsten Tage hier auf Github veröffentlichen, ich kann allerdings nicht zu jeder Version den Quellcode hochladen, da ich fast nie Backups erstellt habe. Eine PayPal.Me Addrese besitze ich und werde sie dir auch schicken sobald ich die Builds hochgeladen habe.
Was genau meinst du mit den Versionsinformationen, die build.gradle Dateien habe ich nie Manuell bearbeitet?

**Comment by IzzySoft** [comment]
@MarvinStelter wir brauchen nicht alle Tags (warum sollten wir alle "Alt-Versionen" bauen? Unser Buildserver ist ohnehin schon am Schwitzen :rofl:), die aktuelle Version genügt für's erste (dann aber "am Ball bleiben" mit den Folgeversionen; F-Droid erstellt die Apps aus den Quellen, die werden also gebraucht).

Was Kerstin mit den Versionsinfos meint: Wo hast Du denn `versionCode` und `versionName` definiert? Finde ich weder im Manifest, noch in der `build.gradle`. Normalerweise stehen die in `app/build.gradle`, aber die Datei gibt es in Deinem Repo gar nicht. Oder im Manifest – da fehlen diese Angaben jedoch ebenfalls.

Spenden-Adresse: Bitte (alle) auch im Readme hier vermerken, damit sie verifizierbar sind. Neben PayPal sind da auch Dinge wie Liberapay, Bitcoin und Litecoin möglich…

Oh, Disclosure vergessen: Ich bin einer der F-Droid Maintainer.

**Comment by IzzySoft** [comment]
Bist Du noch dran? Fast 2 Jahre später, aber ich sehe noch immer keine Tags. Wäre auch toll, wenn Du [Fastlane Strukturen](https://gitlab.com/snippets/1895688) etablieren könntest (mindestens `short_description.txt` und `full_description.txt` für `fastlane/metadata/android/en-US` wären nötig, idealerweise auch für `de` und Screenshots).

**Comment by KerstinMaur** [comment]
Mit der Fastlane Struktur kann ich dir auch helfen, @MarvinStelter. Ich würde einfach die Daten von [Google Play](https://play.google.com/store/apps/details?id=de.msdevs.einschlafhilfe) nehmen und hier einen PR erstellen. Was meinst du? Ich hoffe, dass du diese geniale App noch nicht aufgegeben hast.

**Comment by DonMarv00** [comment]
Hi, falls ihr die App immer noch auf F-Droid hochladen wollt könnt ihr dies nun tun. 
Ich habe den Code bearbeitet und erneut hochgeladen, ein Release habe ich auch erstellt. Wäre cool wenn ihr mir dann mit der Fastlane Struktur helfen würdet. @KerstinMaur @IzzySoft

**Comment by IzzySoft** [comment]
@MarvinStelter ich hätte Dir mit der Fastlane-Struktur ja gern geholfen – aber Dein Repo hat weder eine Summary, noch eine Beschreibung – oder gar Screenshots. Ich wüsste also gar nicht, was ich da in die [Fastlane Struktur](https://gitlab.com/snippets/1895688) integrieren sollte. Was auch definitiv fehlt und einen echten Show-Stopper darstellt ist die **fehlende Lizenz.**

Für Fastlane bliebe nur, sich bei Deinem Play Store Listing zu bedienen. Siehe #2

PS: Das App Bundle (`*.aab`) ins Repo einzuchecken ist eine schlechte Idee. Wer immer zu Deinem Projekt beitragen möchte muss unnötigerweise auch das Binary inkl. aller History mit clonen. Das gehört besser ans Release angehängt :wink: Geschmackssache ist das Framen der Screenshots: überlege einmal, was die Betrachter auf dem 5" Bildschirm eines Smartphones davon noch als Details wahrnehmen – da geht durch den "Frame" wertvoller "Screen Estate" verloren.

**Comment by IzzySoft** [comment]
Btw: Hast Du Dich mittlerweile für eine Lizenz entschieden? Irgendwie finde ich im Repo keine vermerkt…

**Comment by DonMarv00** [comment]
Hab's erledigt

**Comment by IzzySoft** [comment]
Super, Danke! Hab's in meinem Repo angepasst. Damit sollte jetzt einem Versuch, die App direkt bei F-Droid.org unterzubringen, eigentlich nichts mehr entgegenstehen – können wir also gern in Angriff nehmen.

**Comment by IzzySoft** [comment]
@MarvinStelter I've tried adding your app to F-Droid directly as originally requested – but the app crashes right at start. Any ideas? Logcat:

```
E/AndroidRuntime(29834): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(29834): Process: de.msdevs.einschlafhilfe, PID: 29834
E/AndroidRuntime(29834): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(29834):    at android.os.AsyncTask$4.done(AsyncTask.java:415)
E/AndroidRuntime(29834):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(29834):    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(29834):    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(29834):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
E/AndroidRuntime(29834):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(29834):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(29834):    at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(29834): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/AndroidRuntime(29834):    at java.io.StringReader.<init>(StringReader.java:50)
E/AndroidRuntime(29834):    at de.msdevs.einschlafhilfe.MainActivity$folgen_daten_laden.doInBackground(MainActivity.java:263)
E/AndroidRuntime(29834):    at de.msdevs.einschlafhilfe.MainActivity$folgen_daten_laden.doInBackground(MainActivity.java:254)
E/AndroidRuntime(29834):    at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/AndroidRuntime(29834):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

Full report here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10843

**Comment by DonMarv00** [comment]
Habe die App heute zu Kotlin portiert und werde das am Wochenende hochladen , der Fehler sollte damit behoben sein!

**Comment by IzzySoft** [comment]
Prima! Sobald die CI dann durch ist, wede ich wieder schauen. Danke Dir!

**Comment by DonMarv00** [comment]
Hab's hochgeladen, du kannst es testen

**Comment by IzzySoft** [comment]
Hoppla, da hat mich eine Benachrichtigung nicht erreicht – gut, dass ich ein "due date" auf das Issue bei uns gesetzt und jetzt manuell gecheckt habe. Da muss ich dann gleich nochmal schauen…

YAML updated, build running. Melde mich später nochmal.

**Comment by IzzySoft** [comment]
OK, da bin ich wieder. Läuft jetzt stabil, [aaaber](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10843#note_931659407)…

* was macht die App bei 85.13.165.24 (dd49130.kasserver.com), wenn man sie das erste Mal startet?
* benötigt sie tatsächlich den offiziellen Spotify-Client (dann brauchen wir auch noch NonFreeDep)? Alternativ gäbe es ja auch noch Apps wie [Spotube](https://apt.izzysoft.de/fdroid/index/apk/oss.krtirtho.spotube).

Kannst Du das (Spotify App / Spotube) bitte auch noch in der `full_description.txt` erwähnen? Dort ist die Abhängigkeit derzeit nicht ersichtlich.

**Comment by DonMarv00** [comment]
Mit dd49130.kasserver.com wird ein Json Script heruntergeladen.
Spotify ist nicht zwangsmöglich notwendig, aber im Google Play Store release vorhanden.

Ich kann ein neues Branch für die F Droid Version erstellen, die dann offline ist und Spotube benutzt.

**Comment by IzzySoft** [comment]
> Mit dd49130.kasserver.com wird ein Json Script heruntergeladen.

Hm, und das ließe sich nicht direkt in der App integrieren? Falls nicht, sollte es vielleicht irgendwie kenntlich gemacht werden. Wie oft passiert das denn? Vielleicht eine einmalige Abfrage/Hinweis beim ersten Mal?

> Ich kann ein neues Branch für die F Droid Version erstellen, die dann offline ist und Spotube benutzt.

Oder die Wahl lässt, welche App aufgerufen werden soll. Damit würde dann NonFreeDep entfallen. NonFreeNet bliebe wahrscheinlich dennoch, da letztendlich ja doch von Spotify gestreamt wird. Ein kurzer Hinweis in der Beschreibung wäre sicher auch gut.

Danke schonmal!

**Comment by DonMarv00** [comment]
Die Abfrage passiert nach jedem App start, ich werde das aber ändern und den Nutzer die Möglichkeit geben die Daten manuell zu aktualisieren.

Die Auswahl zwischen Spotube und Spotify werde ich auch einbauen, ich schreibe dir dann hier nochmals.

**Comment by IzzySoft** [comment]
Super, Danke Dir!

**Comment by IzzySoft** [comment]
@MarvinStelter wie ist denn jetzt der Stand? Dein RFP poppt gerade in der Triage auf, da einen Monat inaktiv. Ich schiebe ihn jetzt mal zwei Wochen weiter, damit Du noch eine Chance hast. Wäre schön wenn wir das fertig bekämen :wink:

**Comment by DonMarv00** [comment]
Bin momentan dran, ich werde das am Wochenende alles fertig haben.

**Comment by IzzySoft** [comment]
Super – dann wünsche ich schonmal gutes Gelingen!

**Comment by DonMarv00** [comment]
Update: Habe jetzt 95% fertiggestellt, brauche noch 1-2 Tage

**Comment by IzzySoft** [comment]
Kein Thema, zur Not "shifte" ich das due-date nochmal :smile:

**Comment by DonMarv00** [comment]
Der Nutzer kann nun auswählen ob die App nun komplett offline laufen soll oder Daten laden darf.
Der Spotify Button kann nun ausgeblendet werden.

Die Optionen werden den Nutzer bei dem ersten Öffnen angezeigt, nachträglich geht das auch in den App Einstellungen. 

Habe die Beschreibung angepasst und darüber informiert das Spotify möglicherweise Daten sammelt sobald es benutzt wird.

**Comment by IzzySoft** [comment]
Dann warten wir jetzt nur noch auf ein neues Tag nehme ich an? Oder zeigen wir statt auf den commit 5b53874cb153d35099f1ead5924cc191b5d3fe7c auf den vom Tag 4.0 (und alle offenen Punkte sind dort adressiert)? Edit: Letzteres habe ich gerade gemacht, Bestätigung wäre trotzdem lieb :wink:

PS: Sorry für die späte Rückmeldung, irgendwie muss ich die letzte Benachrichtigung im Juni verpasst haben…

**Comment by IzzySoft** [comment]
Oh weh, jetzt hagelt es Fehler (siehe https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10843#note_1122937396):

* Fastlane: short_description ist zu lang (max: 80 Zeichen)
* ein Sack voller Blobs ist da ausgekippt: hast Du versehentlich Build Artifakte mit eingecheckt? Die Blobs liegen alle unter `app/build/`.

Für letzteres habe ich den commit auf den letzten derzeitigen gesetzt (1cdc2ae9d6b98d4824d6507fb47215a1230f3128; der PR hat offensichtlich aufgeräumt). Die shortdesc möchtest Du sicher trotzdem anpassen, da sie sonst abgeschnitten wird. Vorschlag:

* select a random episode of the audiobook "Three Investigators"
* wähle eine zufällige Folge aus dem Hörspiel "Die drei Fragezeichen"

**Comment by DonMarv00** [comment]
Hi,

deine Vorschläge können wir gerne benutzen.
Ich werde (voraussichtlich) morgen ein neues release erstellen, wenn das bei mir zeitlich passt.
Ich gebe dir dann nochmals bescheid.

Gruß

**Comment by IzzySoft** [comment]
:wave: Kein Bescheid? Und kein Release? Auch keine neuen Commits?

**Comment by DonMarv00** [comment]
War eigentlich mein Plan, leider kam etwas dazwischen.
Mein Entwickler Konto bzw. eines davon wurde gelöscht, wahrscheinlich werden jetzt alle gelöscht.
Da ich keinen Fehler gemacht habe bzw. der Grund nicht stimmen kann (Laut Google hatte ich bereits einen gebannten Account, was nachweißlich nicht stimmt) kümmere ich mich momentan darum.

Sobald sich das geregelt hat melde ich mich.

**Comment by IzzySoft** [comment]
Urgs. Dann "first things first (and not necessarily in that order)". Ich drück Dir die Daumen!

**Comment by IzzySoft** [comment]
Ein frohes neues Jahr – und hoffentlich frohe Erfolgsmeldungen? Konntest Du Dein Konto wieder herstellen? Und bekommen wir die App noch fertig bei F-Droid?

**Comment by KerstinMaur** [comment]
> War eigentlich mein Plan, leider kam etwas dazwischen. Mein Entwickler Konto bzw. eines davon wurde gelöscht, wahrscheinlich werden jetzt alle gelöscht. Da ich keinen Fehler gemacht habe bzw. der Grund nicht stimmen kann (Laut Google hatte ich bereits einen gebannten Account, was nachweißlich nicht stimmt) kümmere ich mich momentan darum.
> 
> Sobald sich das geregelt hat melde ich mich.

Wohl fast jeder Entwickler bei Google Play hat ähnliche Probleme. Deswegen wäre ein Release bei F-Droid besonders cool. 😅
Hoffentlich klappt es.
Gebt Bescheid, falls ich irgendwie helfen kann.

**Comment by IzzySoft** [comment]
> Wohl fast jeder Entwickler bei Google Play hat ähnliche Probleme.

Jupp, kaum eine Woche vergeht ohne dass man davon liest. Manchmal gibt es sogar Serials: [Your app is not compliant with Google Play Policies: A story from hell](https://sylviavanos.nl/blog/2021/12/24/google_play_hell.html)… Wenn sich bzgl. Deiner Konten noch immer nix getan hat – vielleicht ist das ein Zeichen, dass Du G den Finger zeigen und die App zu F-Droid bringen solltest? :wink:

**Comment by IzzySoft** [comment]
Ein weiteres Quartal ist vergangen, ohne dass ein neues Release (oder ein neuer Commit) da ist. Das lässt mir nur noch die letzte Option: Der MR wird jetzt als "Schließ-Kandidat" markiert. Wenn in den nächsten 4 Wochen auch kein Feedback mehr kommt, wird er abgebrochen – da keine Aussicht auf "Erfüllung & Merge" zu bestehen scheint :cry:

**Comment by IzzySoft** [comment]
Sorry dann; ich werde den MR jetzt schließen. Schade.

**Comment by KerstinMaur** [comment]
Hoffentlich ist @MarvinStelter nichts Schlimmes zugestoßen...

**Comment by IzzySoft** [comment]
Das hoffe ich auch! Gar keine Antwort über so lange Zeit ist schon seltsam. Aber nach seinem "Aktivitätsgraph" hier bei Github war er zumindest noch vor zwei Wochen hier unterwegs. Zwar in "private repositories", aber das ist ja auch ein Lebenszeichen.

**Comment by DonMarv00** [comment]
Vorweg: Mir geht's recht gut.
So lange keine Antwort gegeben zu haben, war nicht höflich. Dies bitte ich zu entschuldigen.
Ich bin sehr schlecht in Antworten, besonders wenn ich privat bzw. beruflich gestresst bin. Das ist dann so wie eine Blockade.
Das, die Sperrung von Google (Die tatsächlich aufgehoben worden ist.) und andere Pflichten denen ich nachgehen muss hat mir in den letzten Monaten den Spaß genommen.
Aus diesem Grund habe ich 95% meiner entwickelten Apps offline genommen, schon vor ein paar Monaten.

Github benutze ich momentan nur selten und dann eher wegen der Universität.
Schade das es nicht geklappt hat, leider ist dies momentan nicht möglich.
Ich danke euch dennoch für eure Bemühungen! :)

**Comment by IzzySoft** [comment]
Danke für Deine Antwort, Marvin – und gut zu lesen dass es Dir gut geht! Wie Kerstin schon andeutete, das ist doch erst einmal das Wichtigste. Dass es mit der App nun nicht geklappt hat: tja, schade. Solltest Du doch mal wieder Lust bekommen, melde Dich einfach – und wir versuchen einen neuen Start. Geht auch ohne Google, wie Du weißt :see_no_evil:
