### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by TheBiostarfly** [MarvinStelter/DieDreiFragezeichenEinschlafhilfe#4]
**Bug**
After the last update the app is crashing when i try to start it. 

**Smartphone:**
 - Device: Pixel 6 with GraphenOS
 - OS: Android 12
 - Variant Google Play
 - Version: 4.0

**Comment by DonMarv00** [comment]
Do you've an active internet connection ? I'll release an update with some changes in the next days

**Comment by TheBiostarfly** [comment]
Yes thanks that did the job. Just one question why does the app need an internet connection? What has changed?

**Comment by DonMarv00** [comment]
it's for updating content without updating the app and the images needed always an active internet connection! pushed a new update today which should remove all errors
