### ISSUE TITLE
Short descriptions too long

### ISSUE THREAD

**Issue by IzzySoft** [MarvinStelter/DieDreiFragezeichenEinschlafhilfe#6]
Looks like both `short_description.txt` files exceed the limit of 80 chars and thus are truncated mid-term. May I suggest to adjust them to…

* `de`: "hilft dir bei der Auswahl einer Folge des Hörspiels "Die drei Fragezeichen""
* `en-US`: "helps you to select a random episode of the audiobook "Three Investigators""

No need to state the obvious: it's an app, alright :wink:

Thanks!

**Comment by IzzySoft** [comment]
@MarvinStelter :raising_hand_man: 

![image](https://github.com/MarvinStelter/DieDreiFragezeichenEinschlafhilfe/assets/6781438/8d410a4e-e155-42eb-ac15-b3cad28c86a3)

from a report I just received asking what's wrong in my repo :wink:

So again, I corrected that on my end now removing the leading "this app". Please stay within the Fastlane specs which say "max 80 chars" for short description. See my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for details and reference. Thanks!

**Comment by DonMarv00** [comment]
Sollte so nun passen laut cheat sheet

**Comment by IzzySoft** [comment]
LGTM, Danke!
